schedules:
    - name: lawn
      zone: 1
      length: 45
      days:
        - Wednesday
        - Friday
        - Sunday
      timing:
        - "2:00"
        - "3:00"
        - "6:00"
    - name: shrubs
      zone: 2
      length: 30
      days:
        - Thursday
        - Sunday
      timing:
        - "2:45"
        - "7:45"
    - name: pond
      zone: 3
      length: 60
      days:
        - Thursday
      timing:
        - "1:00"
        - "3:30"
        - "6:30"
    - name: pond_east_bank
      zone: 5
      length: 60
      days:
        - Wednesday
      timing:
        - "1:00"
        - "4:00"
        - "8:00"
    - name: east_section
      zone: 6
      length: 60
      days:
        - Saturday
      timing:
        - "3:30"
        - "6:00"
        - "8:30"
    - name: citrus
      zone: 9
      length: 60
      days:
        - Monday
        - Friday
      timing:
        - "1:00"
        - "4:00"
        - "7:00"
    - name: far_section
      zone: 10
      length: 60
      days:
        - Sunday
      timing:
        - "1:00"
        - "4:00"
        - "7:15"